Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Network: Private IP
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", auto_config: true

  # --- PORT FORWARDING ---
  # Jenkins: Guest 8080 -> Host 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  
  # Your App: Guest 8089 -> Host 8089
  config.vm.network "forwarded_port", guest: 8089, host: 8089

  # Nexus: Guest 8081 (Container) -> Host 8082 (Windows)
  # We use 8082 on Windows because 8081 is busy.
  config.vm.network "forwarded_port", guest: 8081, host: 8082

  # SonarQube: Guest 9000 -> Host 9000
  config.vm.network "forwarded_port", guest: 9000, host: 9000

  # Hardware
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 6144
    vb.cpus = 2
  end

  # Setup Script (Basic Tools)
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get install -y gedit curl git

    # Install Kubectl
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    # Install Minikube
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
  SHELL
end