/** Liste des départements / services hospitaliers (création utilisateurs & filtres). */
export const HOSPITAL_DEPARTMENTS = [
  "Cardiologie",
  "Chirurgie",
  "Chirurgie orthopédique",
  "Dermatologie",
  "Endocrinologie",
  "Gastro-entérologie",
  "Gynécologie",
  "Médecine interne",
  "Neurologie",
  "Ophtalmologie",
  "ORL",
  "Pédiatrie",
  "Pneumologie",
  "Psychiatrie",
  "Radiologie",
  "Réanimation",
  "Rhumatologie",
  "Urologie",
  "Urgences",
  "Bloc opératoire",
  "Dialyse",
  "Gériatrie",
  "Oncologie",
];
