apiVersion: v1
kind: Service
metadata:
  name: medifollow-frontend-service
  namespace: medifollow-staging
spec:
  type: NodePort
  selector:
    app: medifollow-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
